# -*- coding: utf-8 -*-
"""Assignment 3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZMyZk9gF--3rkSU61pEge5RbymU5NKtD
"""

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
path='/content/drive/MyDrive/penguins_size (1).csv'
df= pd.read_csv(path)
print(df.head())

import matplotlib.pyplot as plt
import seaborn as sns
plt.figure(figsize=(8, 6))
sns.histplot(df.culmen_length_mm , kde=True)
plt.title("Distribution of Bill Length (mm)")
plt.xlabel("Bill Length (mm)")
plt.ylabel("Frequency")
plt.show()

plt.figure(figsize=(8, 6))
sns.scatterplot(df.culmen_depth_mm)
plt.title("Relationship between Bill Length and Bill Depth")
plt.xlabel("Bill Length (mm)")
plt.ylabel("Bill Depth (mm)")
plt.show()

sns.pairplot(df, hue='species')
plt.suptitle("Pair Plot of Penguin Features by Species")
plt.show()

import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
from scipy import stats

descriptive_stats = df.describe()
print(descriptive_stats)

missing_values = df.isnull().sum()
print("Missing Values:")
print(missing_values)

from scipy import stats

z_scores = stats.zscore(df)
threshold = 3
outliers = (z_scores > threshold).all(axis=1)

df[outliers] = df.median()

correlation_matrix = df.corr()
target_correlation = correlation_matrix['target_column_name']

categorical_columns = df.select_dtypes(include=['object']).columns

X = df.drop('target_column_name', axis=1)
y = df['target_column_name']
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.2, random_state=42)

print("Training data shape:", X_train.shape, y_train.shape)
print("Testing data shape:", X_test.shape, y_test.shape)

