# -*- coding: utf-8 -*-
"""Assigment-1

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OdbH5KF_kgrYA7VEk_oosNYoVArH6014
"""

df = pd.DataFrame(data, columns=['Random value 1', 'Random value 2', 'Random value 3', 'Random value 4'])
print(df)

import pandas as pd
import numpy as np
num_features = 4
num_observations = 4
data = np.random.rand(num_observations, num_features)
df = pd.DataFrame(data, columns=['Feature1', 'Feature2', 'Feature3', 'Feature4'])
print(df)



description = df.describe()
print("\nDescriptive statistics of 'df':")
print(description)

null_values = df.isnull().sum()
print("\nNull Values:")
print(null_values)

data_types = df.dtypes
print("\nData Types:")
print(data_types)

#done by Devadharshika
print("\n'Random value 2' and 'Random value 3' columns using .loc:")
print(df.loc[:, ['Random value 2', 'Random value 3']])

print("\n'Random value 2' and 'Random value 3' columns using .iloc:")
print(df.iloc[:, [1, 2]])